cmake_minimum_required(VERSION 4.1)
project(Hard)

set(CMAKE_CXX_STANDARD 20)

add_executable(Hard cresc.cpp
        Arhitectura2.cpp
        Divizori4.cpp
        pluton.cpp
        poza1.cpp
        nextprob.cpp
        puzzle1.cpp
        Mario1.cpp
        BossFight.cpp
        " Fata Morgana.cpp"
        gard2.cpp)
