cmake_minimum_required(VERSION 4.1)
project(Medium)

set(CMAKE_CXX_STANDARD 20)

add_executable(Medium Unice1.cpp
        gama.cpp
        nthodd.cpp
        ntheven.cpp
        SumaXL.cpp
        Triunghiuri.cpp
        UEMM.cpp
        stergere.cpp
        stergere1.cpp
        inserare3.cpp
        stergere2.cpp
        inserareDupa.cpp
        inserareInainte.cpp
        aceeasi_paritate_2.cpp
        PermCirc.cpp
        Numere2.cpp
        Inaltimi.cpp
        "Sortare Divizori.cpp"
        SortPIE.cpp
        sortMinMax.cpp
        sortPP.cpp
        SortSD.cpp
        CifInit.cpp
        CifMin.cpp
        Produse.cpp
        HalfSort.cpp
        SortSum.cpp
        Partitionare.cpp
        HalfSort2.cpp
        HalfSort3.cpp
        HalfSort4.cpp
        Sort_Indici.cpp
        AsEasyAsABC.cpp
        Divigrup.cpp
        PuteriK.cpp
        OrdSume.cpp
        CRB.cpp
        sortare_in_trepte.cpp
        VocaleVector.cpp
        Memory007.cpp)
