cmake_minimum_required(VERSION 4.1)
project(Easy)

set(CMAKE_CXX_STANDARD 20)

add_executable(Easy Paritate1.cpp
        Afisare0.cpp
        Inlocuire5.cpp
        " Afisare.cpp"
        MinMax0.cpp
        Numarare6.cpp
        pv.cpp
        NumararePIE.cpp
        NumarareDiv.cpp
        ElemPP.cpp
        Sume.cpp
        DivFactorial.cpp
        Pozitie.cpp
        PozitieX.cpp
        Stergere_Element.cpp
        ElimRep.cpp
        inserare.cpp
        aceeasi_paritate.cpp)
