cmake_minimum_required(VERSION 4.1)
project(Easy)

set(CMAKE_CXX_STANDARD 20)

add_executable(Easy Paritate1.cpp
        Afisare0.cpp
        Inlocuire5.cpp
        " Afisare.cpp"
        MinMax0.cpp
        Numarare6.cpp
        pv.cpp
        NumararePIE.cpp
        NumarareDiv.cpp
        ElemPP.cpp
        Sume.cpp
        DivFactorial.cpp
        Pozitie.cpp
        PozitieX.cpp
        Stergere_Element.cpp
        ElimRep.cpp
        inserare.cpp
        aceeasi_paritate.cpp
        Ordonare.cpp
        SortPrime.cpp
        Sort10.cpp
        Arhitectura.cpp
        KSort.cpp
        SortMax.cpp
        Sortare.cpp
        SortCif.cpp
        alfa.cpp
        SortCif2.cpp
        Sort2.cpp
        PareSort.cpp
        numere16.cpp)
